// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvjjujgljjtwjqlvpqoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2amp1amdsamp0d2pxbHZwcW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Nzk1MzIsImV4cCI6MjA3MTQ1NTUzMn0.2HMFNboSBpotiI9NozHG22QeIwedyTOP4uw8sV6vABs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});